# Generated by Django 5.2.6 on 2025-12-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_birth_date_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investment_persona',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
