# Generated by Django 5.2.9 on 2025-12-23 07:21

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings  # <--- 이 줄이 꼭 있어야 합니다!

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_userportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('deposit', '정기예금'), ('saving', '적금'), ('annuity', '연금저축'), ('mortgage', '주택담보대출'), ('rent', '전세자금대출'), ('credit', '개인신용대출')], default='deposit', max_length=20),
        ),
        migrations.AddField(
            model_name='productoption',
            name='etc_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='save_trm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='liked_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
