# Generated by Django 5.2.9 on 2025-12-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_type_productoption_etc_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='etc_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='join_deny',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='join_member',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='join_way',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='spcl_cnd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='intr_rate_type_nm',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
