# Generated by Django 5.2 on 2025-12-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_etc_note_alter_product_join_deny_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_users',
        ),
    ]
