# Generated by Django 5.2.6 on 2025-12-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('deposit', '정기예금'), ('saving', '적금'), ('annuity', '연금저축'), ('mortgage', '주택담보대출'), ('rent', '전세자금대출'), ('credit', '개인신용대출'), ('etf', 'ETF/주식')], default='deposit', max_length=20),
        ),
    ]
